<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:test-suite start="1501833867869" stop="1501834028554" xmlns:ns2="urn:model.allure.qatools.yandex.ru">
    <name>Suite : Test2[excelName=data.xls, excelSheet=Sheet1]</name>
    <title>Suite : Test2[excelName=data.xls, excelSheet=Sheet1]</title>
    <test-cases>
        <test-case start="1501833983402" stop="1501834028455" status="failed">
            <name>loginFunc[sunaina@test.com,12345678]</name>
            <failure>
                <message>AssertionError: Expected: failed</message>
                <stack-trace>java.lang.AssertionError: Expected: failed
	at test.LoginPageTest2.loginFunc(LoginPageTest2.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
</stack-trace>
            </failure>
            <steps>
                <step start="1501833983402" stop="1501834027220" status="failed">
                    <name>loginFunc[sunaina@test.com, 12345678]</name>
                    <title>User open Meritnation.com, enter credentials, click on login button</title>
                </step>
            </steps>
            <attachments>
                <attachment title="loginFunc" source="04ae89e9-8412-4f98-8d98-6e6c907272d1-attachment.png" type="image/png"/>
                <attachment title="loginFunc" source="dadcc844-045d-4395-9b91-5bbdfe7021a3-attachment.png" type="image/png"/>
            </attachments>
            <labels>
                <label name="severity" value="critical"/>
                <label name="story" value="Login with valid credentials"/>
                <label name="feature" value="Meritnation Login"/>
                <label name="host" value="XE-T-DEEPAKS"/>
                <label name="thread" value="3180@XE-T-DEEPAKS.TestNG-tests-2(13)"/>
            </labels>
        </test-case>
    </test-cases>
    <labels>
        <label name="framework" value="TestNG"/>
        <label name="language" value="JAVA"/>
    </labels>
</ns2:test-suite>
